import type { Metadata } from "next";

import { Toaster } from "@/components/ui/toaster";
import "./globals.css";

export const metadata: Metadata = {
  title: "Load Bank IoT",
  description: "Generated by DB",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body>
        <main className={`w-3/4 flex justify-center content-center align-middle max-h-screen overflow-scroll`}>
          {children}{" "}
        </main>

        <Toaster />
      </body>
    </html>
  );
}
